name: Gradlew build, publish to npm registry and sonar-analysos
on:
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - '!release-branch'
      - release*
      - master
      - 1.*
      - develop*
      - MOSIP*
jobs:
  build-mosip-sbi-capacitor:
    uses: mosip/kattu/.github/workflows/npm-android-build.yml@master
    with:
      SERVICE_LOCATION: 'mosip-sbi-capacitor'
      ANDROID_LOCATION: 'android'
      BUILD_ARTIFACT: mosip-sbi-capacitor
      GRADLEW_ARGS: 'clean build test'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  publish-mosip-sbi-capacitor-to-npm-registry:
    if: "${{ !contains(github.ref, 'master') && github.event_name != 'pull_request' }}"
    needs: build-mosip-sbi-capacitor
    uses: mosip/kattu/.github/workflows/npm-publish-to-npm-registry.yml@master
    with:
      SERVICE_LOCATION: 'mosip-sbi-capacitor'
      ANDROID_LOCATION: 'android'
      GRADLEW_ARGS: 'clean build test'
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  sonar-analysis-sbi-capacitor-plugin:
    if: "${{ github.event_name != 'pull_request' }}"
    needs: build-mosip-sbi-capacitor
    uses: mosip/kattu/.github/workflows/gradlew-sonar-analysis.yml@master
    with:
      SERVICE_LOCATION: 'mosip-sbi-capacitor'
      ANDROID_LOCATION: 'android'
      SONAR_URL: 'https://sonarcloud.io'
      PROJECT_KEY: "mosip_${{ github.event.repository.name }}"
      PROJECT_NAME: "${{ github.event.repository.name }}"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_ORGANIZATION: ${{ secrets.ORG_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
